from state import AgentState

# -----------------------------
# Planner Agent
# -----------------------------
def planner_agent(state: AgentState):

    task = state["task"]

    plan = f"""
Plan for the task:

1. Understand the task: "{task}"
2. Gather important information.
3. Create a clear response.
4. Send response to Reviewer Agent for quality check.
"""

    state["plan"] = plan.strip()
    state["history"].append("Planner Agent completed planning.")
    state["steps"] += 1

    return state


# -----------------------------
# Worker Agent
# -----------------------------
def worker_agent(state: AgentState):

    task = state["task"]

    work = f"""
Task: {task}

This response was generated by the Worker Agent.

The worker follows the Planner Agent's instructions and prepares
a detailed explanation for the given task.

The response includes multiple sentences so that it passes the
review quality check and demonstrates collaboration between agents
inside the LangGraph workflow.
"""

    state["work"] = work.strip()
    state["history"].append("Worker Agent completed the work.")
    state["steps"] += 1

    return state


# -----------------------------
# Reviewer Agent
# -----------------------------
def reviewer_agent(state: AgentState):

    work = state["work"]

    # Rule:
    # Reject if work is too short.
    if len(work) < 150:

        state["status"] = "rejected"
        state["reject_count"] += 1

        state["review"] = (
            "Reviewer rejected the work because the response "
            "was too short and lacked sufficient detail."
        )

    else:

        state["status"] = "accepted"

        state["review"] = (
            "Reviewer accepted the work. The response is detailed "
            "and meets the quality requirements."
        )

    state["history"].append(
        f"Reviewer Agent status: {state['status']}"
    )

    state["steps"] += 1

    return state